# fly.toml file generated for hbnb on 2023-01-15T07:36:05-05:00

app = "hbnb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  HBNB_TYPE_STORAGE = 'file'

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  # This MUST match the port(s) in Hbnb's Nginx configuration:
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
