services:
  hbnb:
    build: .
    ports:
      - "8000:8080"
    environment:
      CONFIGURATION: development
      HBNB_FRONTEND_PORT: 8000
      HBNB_API_PORT: 8001
    volumes:
      [
        ./frontend:/app/frontend,
        ./config:/app/config,
      ]
